name: 'coverage'
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - master
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=pywhip --cov-report xml:coverage.xml
      - name: Get Cover 
        uses: orgoro/coverage@d77626a5fa35d39123e86d6c62907fabe2491496 # v3
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
